---
# tasks file for MicrosoftTeams
- name: Get the Token variable
  shell: "kubectl get secret microsoft-graph-token -o jsonpath='{.data.microsoft-graph-token}' | base64 --decode"
  register: token_output

- name: List teams
  uri:
    url: "https://graph.microsoft.com/v1.0/me/joinedTeams"
    method: GET
    headers: 
      Authorization: "Bearer {{ token_output.stdout }}"
    status_code: 200
  register: teams_response
  ignore_errors: true

- name: Introduce a delay
  pause:
    seconds: 10

- name: Set team_id variable
  set_fact:
    team_id: "{{ item.id }}"
  loop: "{{ teams_response.json.value  }}" 
  when: "item.displayName == name"

- name: Introduce a delay
  pause:
    seconds: 10

- name: Delete group
  uri:
    url: "https://graph.microsoft.com/v1.0/groups/{{ team_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ token_output.stdout }}"
    status_code: 204
  ignore_errors: true